// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrakQ.Db;

#nullable disable

namespace TrakQ.Db.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250107183735_InitWithIncomeModels")]
    partial class InitWithIncomeModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TrakQ.Db.Data.Entities.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IncomeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeHeadId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("IncomeId");

                    b.HasIndex("IncomeHeadId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("TrakQ.Db.Data.Entities.IncomeHead", b =>
                {
                    b.Property<int>("IncomeHeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncomeHeadName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("IncomeHeadId");

                    b.ToTable("IncomeHeads");
                });

            modelBuilder.Entity("TrakQ.Db.Data.Entities.Income", b =>
                {
                    b.HasOne("TrakQ.Db.Data.Entities.IncomeHead", "IncomeHead")
                        .WithMany()
                        .HasForeignKey("IncomeHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeHead");
                });
#pragma warning restore 612, 618
        }
    }
}
