// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrakQ.Db;

#nullable disable

namespace TrakQ.Db.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250112093558_AddExpenseTables")]
    partial class AddExpenseTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TrakQ.Db.Data.Entities.Expenditure", b =>
                {
                    b.Property<int>("ExpenditureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpenditureDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpenditureHeadId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentHeadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.HasKey("ExpenditureId");

                    b.HasIndex("ExpenditureHeadId");

                    b.ToTable("Expenditures");
                });

            modelBuilder.Entity("TrakQ.Db.Data.Entities.ExpenditureHead", b =>
                {
                    b.Property<int>("ExpenditureHeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Budget")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FixedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentHeadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExpenditureHeadId");

                    b.ToTable("ExpenditureHeads");
                });

            modelBuilder.Entity("TrakQ.Db.Data.Entities.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IncomeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeHeadId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("IncomeId");

                    b.HasIndex("IncomeHeadId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("TrakQ.Db.Data.Entities.IncomeHead", b =>
                {
                    b.Property<int>("IncomeHeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncomeHeadName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("IncomeHeadId");

                    b.ToTable("IncomeHeads");
                });

            modelBuilder.Entity("TrakQ.Db.Data.Entities.Expenditure", b =>
                {
                    b.HasOne("TrakQ.Db.Data.Entities.ExpenditureHead", "ExpenditureHead")
                        .WithMany()
                        .HasForeignKey("ExpenditureHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenditureHead");
                });

            modelBuilder.Entity("TrakQ.Db.Data.Entities.Income", b =>
                {
                    b.HasOne("TrakQ.Db.Data.Entities.IncomeHead", "IncomeHead")
                        .WithMany()
                        .HasForeignKey("IncomeHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeHead");
                });
#pragma warning restore 612, 618
        }
    }
}
